travis:
  secure:
    BINSTAR_TOKEN: NZ7fAnW06V3Epm/2Q/84hwbpw6PgedzLl6dmo2sVp6af9KcKTcTEKw1m4c3JjLh1wTU/Tb3xkmx2vrfqx/UInDNH6OxLH8QlF4CLKG98nMNCkqgSjf2UoqpQhVLIaNRHg44UjnQO40ijl+WmrBZiaiN9XVZ1xXp5sp3ymFI6ub8BRPf6CYXB/BkkvmocXSJ21qwuHj1Zk2n1TmYurpJ3RGDMA7LYDh+WlFptzJLWKDXiC9xYON8k00NtUBPGAJTt9tERtIiDIfCVWmtPQWApnMDw4Ug/hoczAkunF6op+phMZyc0cB6Oiw/PyIJjOcvS2wr+EldAfQegozIYZXnonuR1dImRN8YhAxhOz6Gy05btMNt80wgU977fptf0un6VZXnqkbOZ5AZSSBtcEuEPlDMbBIG865AEK0qC4FokUOMIWvqW8s1ihd+HSy31+2xbdMRAgaA4Fw7l2LYk/o85ygqHI8jSBBKjiNhvlhKmUKnzvB/aLhzr3F0mJr7qAEm5t/3awOaY5r8f3A/47hS8Elkzk5mKGc2f9PwWntxZm9+L2pFnzn1c4wZE72EVSwhiGWJ49SXDgz8ORBWxVnE56T2+uhwz4hM0+ZiZkFUhupfV11bd/hI+Q7XJMWmY7ZEs21jk5OwoQC5/1xJKIHdzxT9eGvyqnF5g++1UjzpyVk0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
